MvcCoreCacheRedis/Models/ErrorViewModel.cs
namespace MvcCoreCacheRedis.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreCacheRedis/Models/Producto.cs
namespace MvcCoreCacheRedis.Models
{
    public class Producto
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Precio { get; set; }
        public string Imagen { get; set; }
    }
}

MvcCoreCacheRedis/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreCacheRedis.Models;

namespace MvcCoreCacheRedis.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreCacheRedis/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreCacheRedis.Models;
using MvcCoreCacheRedis.Repositories;
using MvcCoreCacheRedis.Services;

namespace MvcCoreCacheRedis.Controllers
{
    public class ProductosController : Controller
    {
        private RepositoryProductos repo;

        private ServiceCacheRedis service;

        public ProductosController(RepositoryProductos repo, ServiceCacheRedis service)
        {
            this.repo = repo;
            this.service = service;
        }

        public IActionResult Index()
        {
            List<Producto> productos = this.repo.GetProductos();
            return View(productos);
        }

        public IActionResult Details(int id)
        {
            Producto producto = this.repo.FindProducto(id);
            return View(producto);
        }

        public async Task<IActionResult> Favoritos()
        {
            List<Producto> productos = await this.service.GetProductosFavoritosAsync();
            return View(productos);
        }

        public async Task<IActionResult> SeleccionarFavorito(int idproducto)
        {
            //BUSCAMOS EL PRODUCTO DENTRO DEL REPO
            Producto producto = this.repo.FindProducto(idproducto);
            await this.service.AddProductoFavoritoAsync(producto);
            return RedirectToAction("Favoritos");
        }

        public async Task<IActionResult> DeleteFavorito(int idproducto)
        {
            await this.service.DeleteProductoFavoritoAsync(idproducto);
            return RedirectToAction("Favoritos");
        }
    }
}

MvcCoreCacheRedis/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreCacheRedis/Views/Productos/Details.cshtml
@model MvcCoreCacheRedis.Models.Producto @{    ViewData["Title"] = "Details";} <div class="card" style="width: 18rem;">    <img src="@Model.Imagen" class="card-img-top" alt="...">    <div class="card-body">        <h5 class="card-title">@Model.Nombre</h5>        <p class="card-text">Precio @Model.Precio</p>        <p class="card-text">@Model.Descripcion</p>        <a asp-controller="Productos" asp-action="SeleccionarFavorito" asp-route-idproducto="@Model.IdProducto"        class="btn btn-primary">Seleccionar favorito</a>    </div></div>

MvcCoreCacheRedis/Views/Productos/Favoritos.cshtml
@model IEnumerable<MvcCoreCacheRedis.Models.Producto>

@{
    ViewData["Title"] = "Favoritos";
}

<h1>Favoritos Cahe Redis</h1>

@if(Model != null){
    <table class="table table-bordered table-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdProducto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Precio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    <td>
                        <img src="@item.Imagen" style="width:100px; height:100px;" />
                    </td>
                    <td>
                        <a asp-controller="Productos" asp-action="DeleteFavorito" asp-route-idproducto="@item.IdProducto" class="btn btn-danger">Quitar favorito</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreCacheRedis/Views/Productos/Index.cshtml
@model IEnumerable<MvcCoreCacheRedis.Models.Producto>

@{
    ViewData["Title"] = "Index";
}

<h1>Productos</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>Detalles</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <img src="@item.Imagen" style="width:100px; height:100px;"/>
            </td>
            <td>
               <a asp-controller="Productos" asp-action="Details" asp-route-id="@item.IdProducto" class="btn btn-info">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreCacheRedis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreCacheRedis</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreCacheRedis.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreCacheRedis</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Favoritos">Favoritos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcCoreCacheRedis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>